# Generated by Django 5.1.15 on 2026-01-20 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_request_association'),
        ('organizations', '0005_alter_association_logo_url'),
        ('regions', '0002_seed_bc_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contactrequest',
            name='unique_pending_request_per_player_association',
        ),
        migrations.AddConstraint(
            model_name='contactrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('requesting_association__isnull', False), ('status', 'pending')), fields=('player', 'requesting_association'), name='unique_pending_request_per_player_association'),
        ),
    ]
