# Generated by Django 5.1.15 on 2026-01-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_association_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Square logo URL, recommended 200–800px.'),
        ),
    ]
