# Generated by Django 5.1.15 on 2026-01-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_association_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='logo',
            field=models.ImageField(blank=True, help_text='Square image, 200–800px.', upload_to='associations/logos/'),
        ),
    ]
