# Generated by Django 5.1.15 on 2026-01-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountprofile_phone_number'),
        ('organizations', '0005_alter_association_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='organizations.association'),
        ),
    ]
